"""change user class

Revision ID: b31878d52c42
Revises: 386824c0aca7
Create Date: 2020-03-06 23:24:53.962115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b31878d52c42'
down_revision = '386824c0aca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'authenticated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('authenticated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
